### ISSUE TITLE
modal text cut off on mobile

### ISSUE THREAD

**Issue by FilmCoder** [yayboys/yay#15]
click "contact" on a rep and then toggle iphone 6/7/8 emulation on chrome.  Text is cut off.  Is bootstrap modal not optimized for mobile?

**Comment by FilmCoder** [comment]
Actually, this doesn't seem to be happening in iphone emulation.  but it is happening on my physical phone, samsung s10e

**Comment by smitto** [comment]
It's happening on iPhone 5/SE emulation (not actually cut off, but you have to horizontally scroll), so I'll use that as a reference.

**Comment by smitto** [comment]
This has been "swagged on"

**Comment by FilmCoder** [comment]
As a certain individual would say, "30 thousand 100 trillion"
