### ISSUE TITLE
disable the damn linter

### ISSUE THREAD

**Issue by FilmCoder** [yayboys/yay#3]
it's so annoying, and it won't let me put "debugger" statements in so it makes debugging a pain in the ass.  I couldn't easily figure out how to disable it, I think it's baked in as some sort of vuetify or vue-cli present

**Comment by smitto** [comment]
Hi FilmCoder, thanks for logging this issue! Someone from our expansive dev community will look into it at their earliest availability.

**Comment by FilmCoder** [comment]
Dear Mr. Smitto,

Yeahhhhh if you could go ahead and take this one for me.... That'd be greaaaat.  Thankssss smitto ur a real bud
